CREATE TABLE Genre (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       name VARCHAR(255) NOT NULL,
                       PRIMARY KEY (id)
);

CREATE TABLE Movie (
                       id BIGINT NOT NULL,
                       description VARCHAR(255),
                       poster_url VARCHAR(255),
                       rate_count INTEGER NOT NULL,
                       rate_sum INTEGER NOT NULL,
                       release_date VARCHAR(255),
                       title VARCHAR(255) NOT NULL,
                       PRIMARY KEY (id)
);

CREATE TABLE movie_genre (
                             movie_id BIGINT NOT NULL,
                             genre_id BIGINT NOT NULL,
                             PRIMARY KEY (movie_id, genre_id)
);

CREATE TABLE Review (
                        id BIGINT NOT NULL,
                        content VARCHAR(255),
                        created_at TIMESTAMP(6),
                        rate INTEGER NOT NULL,
                        updated_at TIMESTAMP(6),
                        movie_id BIGINT NOT NULL,
                        user_id BIGINT NOT NULL,
                        PRIMARY KEY (id)
);

CREATE TABLE users (
                       id BIGINT NOT NULL,
                       created_at DATE,
                       email VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       user_role VARCHAR(255) NOT NULL CHECK (user_role IN ('USER','ADMIN')),
                       username VARCHAR(255) NOT NULL,
                       PRIMARY KEY (id)
);

CREATE TABLE Watchlist (
                           id BIGINT NOT NULL,
                           added_at TIMESTAMP(6) NOT NULL,
                           is_watched BOOLEAN NOT NULL,
                           movie_id BIGINT NOT NULL,
                           user_id BIGINT NOT NULL,
                           PRIMARY KEY (id)
);
